#!/usr/bin/env bash
set -euo pipefail

echo "Reference Builder"
echo "================="
echo
echo "This script documents how to generate reusable reference resources"
echo "for the nf-core/riboseq preprocessing workflow."
echo

echo "Reference resources are generated by running nf-core/riboseq once on a small debug dataset."
echo "After the run finishes, copy the generated genome resources into refs/built/<reference_name>/."
echo
echo "Example:"
echo
echo "  bash scripts/run.sh configs/debug.example.config --custom_config_base false"
echo
echo "  mkdir -p refs/built/<reference_name>"
echo "  rsync -av results/debug/genome/ refs/built/<reference_name>/"
echo
echo "After copying, edit your configuration:"
echo
echo "  REF=refs/built/<reference_name>"